### ISSUE TITLE
simout2timetable does not work for multiple output ports (I think is the issue)

### ISSUE THREAD

**Issue by grbn24** [FannoFlow/boost_matlab#1]
[output_2_ports.zip](https://github.com/FannoFlow/boost_matlab/files/5194009/output_2_ports.zip)

Error:
Error using timetable (line 299)
All table variables must have the same number of rows.

Error in constructTimeTableFromNumericTimeVector (line 19)
tt = timetable(Time, data);

Error in simout2timetable (line 43)
    timetables = [timetables, {constructTimeTableFromNumericTimeVector(simout.(NameValueArgs.TimeSaveName),
    simout.(NameValueArgs.OutputSaveName))}];

Error in basic_ilc (line 24)
res = simout2timetable(simout);

**Comment by grbn24** [comment]
I will check it out if I have some free time, but I really should be working on my graduation project

**Comment by FannoFlow** [comment]
error encountered when yout is a 1x1 dataset. 

Will need to improve constructTimeTableFromNumericTimeVector to account for this, probably just change the function sugnature as well.

![image](https://user-images.githubusercontent.com/20805014/92997190-5d64e880-f4df-11ea-8f8a-07f3af267711.png)

**Comment by FannoFlow** [comment]
resolved with  
https://github.com/FannoFlow/boost_matlab/commit/29126a6f663539f2766f3dbb00b150e9d1763e85
